-- Usuario
INSERT INTO SunChoi_usuario(dni,usuario_id,nombre,apellido,direccion,telefono,correo) values('13567',1,'mau','leiton','data de villamil' , '234567','mau_leiton@espol.edu.ec');
-- Roles
INSERT INTO SunChoi_roles(rol,descripcion) values('Administrador','Maneja la app en su totalidad, tiene acceso a todas las funcionalidades implementadas en la app.');
INSERT INTO SunChoi_roles(rol,descripcion) values('Empleado','Acceso limitado, ventas, cotizaciones y poco mas.');
-- UsuarioRol
INSERT INTO SunChoi_usuarioRol(id_usuario,id_rol values(1,1);
-- PROVEEDORES
INSERT INTO SunChoi_proveedores(razon_social,direccion,telefono,email) VALUES('COMSUCRE S.A.','JUAN PIO MONTUFAR 109 Y AGUIRRE','2516315','ventas@comsucre.com');
INSERT INTO SunChoi_proveedores(razon_social,direccion,telefono,email) VALUES('Dilipa CIA LTDA','Av. 10 de Agosto N52-15 y Cap. Ramon Borja','2418640','información@dilipa.com.ec');
-- cliente
INSERT INTO SunChoi_cliente(dni,nombre,apellidos,direccion,telefono) VALUES('0921234567','Julio','Vargas Mendoza','Samanes 6 Mz 200 Vlla 6','2691060');
INSERT INTO SunChoi_cliente(dni,nombre,apellidos,direccion,telefono) VALUES('0917628304','Rosa','Barrios Cardozo','Samanes 6 Mz 198 Vll 14','2948573');
-- productos
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('ACUARELA','ACUARELA LANCER 12 COLORES',2.5,'UND',5,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO BIC CRISTAL NEGRO',0.3,'UND',90,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO BIC CRISTAL AZUL',0.3,'UND',27,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO BIC CRISTAL ROJO',0.3,'UND',59,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO BIC FINO NEGRO',0.4,'UND',17,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO BIC FINO AZUL',0.4,'UND',19,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO BIC FINO ROJO',0.4,'UND',8,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPIZ','LAPIZ BIC HB EVOLUTION',0.35,'UND',35,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPIZ','LAPIZ BIC 12 COLORES CORTO',1.75,'C12',17,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('GOMA EN BARRA','GOMA EN BARRA BIC 8 GRAMOS',1,'UND',11,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPICES DE COLORES','LAPIZ 12 COLORES EVOLUTION ',2.75,'C12',16,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO PELIKAN AZUL',0.4,'UND',10,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO PELIKAN ROJO',0.4,'UND',15,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BOLIGRAFO','BOLIGRAFO PELIKAN NEGRO',0.4,'UND',18,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('BORRADOR','BORRADOR PELIKAN PZ20',0.2,'UND',53,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('CARPETA','CARPETA OFICIO TRANSP. AMARILLA',0.75,'UND',9,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('CARPETA','CARPETA OFICIO TRANSP. NARANJA',0.75,'UND',8,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('CARPETA','CARPETA OFICIO TRANSP. ROSADA',0.75,'UND',9,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('CARPETA','CARPETA OFICIO TRANSP. NEGRA',0.75,'UND',10,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('COMPAS','COMPAS LANCER PRECIS. 13 CMS',1.25,'UND',5,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('GOMA LIQUIDA','GOMA BIOPLAST OFFICE 260 GR',1.25,'UND',12,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('GOMA LIQUIDA','GOMA BIOPLAST SCHOOL 140 GR',0.75,'UND',2,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('GOMA LIQUIDA','GOMA BIOPLAST SCHOOL 50 GR',0.4,'UND',2,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('GOMA','GOMA PELIKAN BARRA PELIFIX 20 GR',1,'UND',12,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPICES DE COLORES','LAPIZ NORMA 12 COLOR',4.25,'C12',12,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPIZ','LAPIZ PELIKAN ESCRITURA 2HB AMARILLO',0.35,'C12',8,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPICES DE COLORES','LAPIZ PELIKAN 12 COLORES',2.5,'C12',12,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPICES DE COLORES','LAPIZ CARIOCA 12 COLORES GRANDE',2,'C12',9,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('LAPICES DE COLORES','LAPIZ CAROCA 12 COLORES PEQUENO',1.25,'C12',12,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM CARNE',0.5,'PLG',9,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM AMARILLO',0.5,'PLG',3,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM AZUL',0.5,'PLG',5,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM AZUL CLARO',0.5,'PLG',7,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM TURQUESA',0.5,'PLG',8,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM ROJO',0.5,'PLG',9,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM VERDE',0.5,'PLG',7,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM GRIS',0.5,'PLG',8,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM NARANJA',0.5,'PLG',11,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM NEGRO',0.5,'PLG',10,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('SILICON','LIQUIDO SILICON LANCER 100 ML',1.5,'UND',10,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('SILICON','LIQUIDO SILICON LANCER 250 ML',1,'UND',13,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('SILICON','LIQUIDO SILICON LANCER 30 ML',0.8,'UND',2,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('SILICON','LIQUIDO SILICON LANCER 60 ML',0.5,'UND',9,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM AZUL',0.75,'UND',10,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM ROJO',0.75,'UND',13,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM NEGRO',0.75,'UND',0,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM VERDE',0.75,'UND',2,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO AZUL',0.75,'UND',14,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO ROJO',0.75,'UND',22,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO NEGRO',0.75,'UND',13,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO VERDE',0.75,'UND',1,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('MARCADORES','MARCAD. COL CARIOCA',1.4,'C6',4,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM NEGRO',0.25,'PLG',18,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM VERDE',0.25,'PLG',18,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM AZUL',0.25,'PLG',28,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM MORADO',0.25,'PLG',13,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM GRIS',0.25,'PLG',13,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM ROJO',0.25,'PLG',14,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM BLANCO',0.25,'PLG',7,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM ANARANJADO',0.25,'PLG',10,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('FOAMY','FOAMY 65X90CM X 2MM VARIOS',0.25,'PLG',12,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('CUADERNO','CUADERNO UNIVERSITARIO 100 HOJAS CUADROS',1.5,'UND',18,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('CUADERNO','CUADERNO UNIVERSITARIO 100 HOJAS 2 LINEAS',1.5,'UND',13,1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock,proveedor_id) VALUES('CUADERNO','CUADERNO UNIVERSITARIO 100 HOJAS 1 LINEA',1.5,'UND',1,1);
