# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='mdleiton@espol.edu.ec', max_length=254),
            preserve_default=False,
        ),
    ]
