# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
