# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='estado',
        ),
    ]
