# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_ventas',
            field=models.FloatField(default=1.55),
            preserve_default=False,
        ),
    ]
