# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('idlog', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('idroles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SunChoi.Roles')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SunChoi.Usuario')),
            ],
        ),
    ]
