# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0002_remove_ordencompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
