# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0003_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='total_proforma',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
