# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0003_auto_20170819_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='ordencompralineas',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facturalineas',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordencompralineas',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
