# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0003_remove_usuario_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='unidad',
            new_name='medida',
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
