# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 04:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0003_auto_20170823_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 4, 9, 46, 854730)),
        ),
    ]
