# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0004_proforma_total_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturalineas',
            name='descuento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturalineas',
            name='iva',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
