# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0004_auto_20170812_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
