# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0004_auto_20170820_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
