# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0005_auto_20170822_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturalineas',
            name='descuento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='facturalineas',
            name='iva',
            field=models.FloatField(),
        ),
    ]
