# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0005_auto_20170812_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='nombre',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(default='ventas@comsucre.com', max_length=200),
            preserve_default=False,
        ),
    ]
