# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0006_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='id_date',
            new_name='fecha',
        ),
    ]
