# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0006_auto_20170822_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompralineas',
            name='descuento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordencompralineas',
            name='iva',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
