# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SunChoi', '0007_auto_20170823_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformalineas',
            name='unidad',
        ),
        migrations.AddField(
            model_name='proformalineas',
            name='descuento',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proformalineas',
            name='iva',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
