INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('ACUARELA','ACUARELA LANCER 12 COLORES',2.5,'UND',5);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO BIC CRISTAL NEGRO',0.3,'UND',90);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO BIC CRISTAL AZUL',0.3,'UND',27);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO BIC CRISTAL ROJO',0.3,'UND',59);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO BIC FINO NEGRO',0.4,'UND',17);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO BIC FINO AZUL',0.4,'UND',19);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO BIC FINO ROJO',0.4,'UND',8);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPIZ','LAPIZ BIC HB EVOLUTION',0.35,'UND',35);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPIZ','LAPIZ BIC 12 COLORES CORTO',1.75,'C12',17);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('GOMA EN BARRA','GOMA EN BARRA BIC 8 GRAMOS',1,'UND',11);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPICES DE COLORES','LAPIZ 12 COLORES EVOLUTION ',2.75,'C12',16);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO PELIKAN AZUL',0.4,'UND',10);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO PELIKAN ROJO',0.4,'UND',15);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BOLIGRAFO','BOLIGRAFO PELIKAN NEGRO',0.4,'UND',18);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('BORRADOR','BORRADOR PELIKAN PZ20',0.2,'UND',53);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('CARPETA','CARPETA OFICIO TRANSP. AMARILLA',0.75,'UND',9);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('CARPETA','CARPETA OFICIO TRANSP. NARANJA',0.75,'UND',8);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('CARPETA','CARPETA OFICIO TRANSP. ROSADA',0.75,'UND',9);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('CARPETA','CARPETA OFICIO TRANSP. NEGRA',0.75,'UND',10);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('COMPAS','COMPAS LANCER PRECIS. 13 CMS',1.25,'UND',5);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('GOMA LIQUIDA','GOMA BIOPLAST OFFICE 260 GR',1.25,'UND',12);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('GOMA LIQUIDA','GOMA BIOPLAST SCHOOL 140 GR',0.75,'UND',2);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('GOMA LIQUIDA','GOMA BIOPLAST SCHOOL 50 GR',0.4,'UND',2);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('GOMA','GOMA PELIKAN BARRA PELIFIX 20 GR',1,'UND',12);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPICES DE COLORES','LAPIZ NORMA 12 COLOR',4.25,'C12',12);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPIZ','LAPIZ PELIKAN ESCRITURA 2HB AMARILLO',0.35,'C12',8);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPICES DE COLORES','LAPIZ PELIKAN 12 COLORES',2.5,'C12',12);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPICES DE COLORES','LAPIZ CARIOCA 12 COLORES GRANDE',2,'C12',9);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('LAPICES DE COLORES','LAPIZ CAROCA 12 COLORES PEQUENO',1.25,'C12',12);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM CARNE',0.5,'PLG',9);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM AMARILLO',0.5,'PLG',3);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM AZUL',0.5,'PLG',5);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM AZUL CLARO',0.5,'PLG',7);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM TURQUESA',0.5,'PLG',8);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM ROJO',0.5,'PLG',9);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM VERDE',0.5,'PLG',7);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM GRIS',0.5,'PLG',8);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM NARANJA',0.5,'PLG',11);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY ESCARCHADO','FOAMY ESCARCH. 65X90CM X 2MM NEGRO',0.5,'PLG',10);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('SILICON','LIQUIDO SILICON LANCER 100 ML',1.5,'UND',10);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('SILICON','LIQUIDO SILICON LANCER 250 ML',1,'UND',13);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('SILICON','LIQUIDO SILICON LANCER 30 ML',0.8,'UND',2);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('SILICON','LIQUIDO SILICON LANCER 60 ML',0.5,'UND',9);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM AZUL',0.75,'UND',10);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM ROJO',0.75,'UND',13);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM NEGRO',0.75,'UND',0);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR PERM','MARCAD. PELIKAN PERM VERDE',0.75,'UND',2);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO AZUL',0.75,'UND',14);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO ROJO',0.75,'UND',22);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO NEGRO',0.75,'UND',13);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADOR SECO','MARCAD. PELIKAN SECO VERDE',0.75,'UND',1);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('MARCADORES','MARCAD. COL CARIOCA',1.4,'C6',4);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM NEGRO',0.25,'PLG',18);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM VERDE',0.25,'PLG',18);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM AZUL',0.25,'PLG',28);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM MORADO',0.25,'PLG',13);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM GRIS',0.25,'PLG',13);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM ROJO',0.25,'PLG',14);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM BLANCO',0.25,'PLG',7);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM ANARANJADO',0.25,'PLG',10);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('FOAMY','FOAMY 65X90CM X 2MM VARIOS',0.25,'PLG',12);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('CUADERNO','CUADERNO UNIVERSITARIO 100 HOJAS CUADROS',1.5,'UND',18);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('CUADERNO','CUADERNO UNIVERSITARIO 100 HOJAS 2 LINEAS',1.5,'UND',13);
INSERT INTO SunChoi_producto(nombre,descripcion,precio_unitario,medida,stock) VALUES('CUADERNO','CUADERNO UNIVERSITARIO 100 HOJAS 1 LINEA',1.5,'UND',1);
